/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jack_learning_ndk_mk_JNIMK */

#ifndef _Included_com_jack_learning_imageprocess_util_ImageUtils
#define _Included_com_jack_learning_imageprocess_util_ImageUtils
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     com_jack_learning_imageprocess_util_ImageUtils
 * Method:    test
 * Signature: Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_jack_learning_imageprocess_util_ImageUtils_test
        (JNIEnv *,jobject);

/*
 * 将传入的图像灰度化
 * Class:     com_jack_learning_imageprocess_util_ImageUtils
 * Method:    gray
 * Signature: I;
 */
JNIEXPORT jint JNICALL Java_com_jack_learning_imageprocess_util_ImageUtils_gray
        (JNIEnv *,jobject,jobject);

/*
 * Class:     com_jack_learning_imageprocess_util_ImageUtils
 * Method:    handleImage
 * Signature: I;
 */
JNIEXPORT jint JNICALL Java_com_jack_learning_imageprocess_util_ImageUtils_handleImage
(JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
